# Conda environment, that includes all packages that are necessary for
# the complete Biotite development process.

name: biotite-dev

channels:
  - anaconda
  - conda-forge
  - salilab
  - bioconda

dependencies:
  - python =3.8
  - setuptools >=30.0
  - pip >=10.0
  - wheel >=0.30
  - requests >=2.12
  - numpy >=1.15
  - scipy >=0.14
  - scikit-learn >= 0.18.0
  - networkx >=2.0
  - pydot >=1.4
  - msgpack-python >=0.5.6
  - cython >=0.29
  - mdtraj >=1.9.3
  - matplotlib >=3.3
  - pytest >=5.2
  - sphinx >=1.7
  - sphinx-gallery =0.7.0
  - numpydoc >=0.8
  - dssp
  - clustalo
  - mafft
  - muscle
  - sra-tools
  - viennarna
  - openbabel
