---
name: Bump version

on:
  workflow_dispatch:
    inputs:
      version:
        description: The new version
        required: true

jobs:
  bump-version:
    name: Bump version
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - run: python .github/workflows/bump_version.py ${{ inputs.version }}
    - uses: peter-evans/create-pull-request@v6.0.4
      with:
        commit-message: Bump version
        delete-branch: true
        title: Bump version to ${{ inputs.version }}
        body: |
          Bump version to ${{ inputs.version }}.
          This pull request was automatically created by the 'Bump version' workflow.
